// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw2N_OLUpdAJW_wQi_9GCkEe7Z90Nn_Fs',
    appId: '1:1051328781525:web:f9d206c4dbbe486e1d565c',
    messagingSenderId: '1051328781525',
    projectId: 'flutterapitest12-358ab',
    authDomain: 'flutterapitest12-358ab.firebaseapp.com',
    databaseURL: 'https://flutterapitest12-358ab-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapitest12-358ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsHqS1t05905JwMPqa_UAOH0nh4X4R5AQ',
    appId: '1:1051328781525:android:af95af706fe34f1b1d565c',
    messagingSenderId: '1051328781525',
    projectId: 'flutterapitest12-358ab',
    databaseURL: 'https://flutterapitest12-358ab-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapitest12-358ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyK9gA_bXilxKr71uYPe4eX7gDcnds10E',
    appId: '1:1051328781525:ios:af382a09b1f2375a1d565c',
    messagingSenderId: '1051328781525',
    projectId: 'flutterapitest12-358ab',
    databaseURL: 'https://flutterapitest12-358ab-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapitest12-358ab.firebasestorage.app',
    iosBundleId: 'com.dummyapps.globalchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyK9gA_bXilxKr71uYPe4eX7gDcnds10E',
    appId: '1:1051328781525:ios:af382a09b1f2375a1d565c',
    messagingSenderId: '1051328781525',
    projectId: 'flutterapitest12-358ab',
    databaseURL: 'https://flutterapitest12-358ab-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapitest12-358ab.firebasestorage.app',
    iosBundleId: 'com.dummyapps.globalchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw2N_OLUpdAJW_wQi_9GCkEe7Z90Nn_Fs',
    appId: '1:1051328781525:web:87cd050619bedbff1d565c',
    messagingSenderId: '1051328781525',
    projectId: 'flutterapitest12-358ab',
    authDomain: 'flutterapitest12-358ab.firebaseapp.com',
    databaseURL: 'https://flutterapitest12-358ab-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapitest12-358ab.firebasestorage.app',
  );

}